[package]
name = "virtue"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-random = "0.1.13"

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1
